mhcomm/pypeman

- pypeman/channels.py
- pypeman/commands.py
- pypeman/nodes.py
As you know, generator node is now possible. A side effect is we can return to next node after a _ConditionSubChannel_. This modification is not active yet, but we should discuss on this new functionality and the possibility to add a new _CaseSubChannel_.
> Generator node now working

- pypeman/channels.py
- pypeman/nodes.py
- pypeman/tests/test_channel.py
- pypeman/tests/test_nodes.py
Add 5 tests for main Base channel usages.
> Add test for channels

- README.md
- docs/gettingstarted.md
- docs/images/source.svg
- docs/userguide.md
- pypeman/channels.py
- pypeman/message.py
- pypeman/msgstore.py
- pypeman/tests/test_channel.py
- pypeman/tests/test_message.py
- pypeman/tests/test_nodes.py
- requirements.txt
- setup.cfg
- setup.py
I've added message store feature by adding one API class `MessageStore` and one implementation, FileMessageStore. More comes after.
> Add message store feature

- CHANGELOG.md
- pypeman/__init__.py
- pypeman/channels.py
- pypeman/nodes.py
- pypi-release-cl.md
- setup.py
Add version, info and checklist to push a release to pypi.
> Prepare for releasing process

- docs/userguide.md
- pypeman/channels.py
- pypeman/commands.py
- pypeman/conf.py
- pypeman/endpoints.py
- pypeman/helpers/reloader.py
- pypeman/msgstore.py
- pypeman/nodes.py
- pypeman/tests/common.py
- pypeman/tests/test_channel.py
- pypeman/tests/test_debug.py
- pypeman/tests/test_nodes.py
- pypeman/tests/tests_bin.py
- setup.py
- tox.ini
Add Sleep, Base64 and email node and fix some problems
> Add differents nodes

- pypeman/channels.py
- pypeman/commands.py
- pypeman/nodes.py
- pypeman/tests/common.py
- pypeman/tests/test_channel.py
- pypeman/tests/test_nodes.py
* Allow subchannel name
* Allow node process as coroutine
* fixes on Email node
* Add tests
> Nodes Fixes

- pypeman/commands.py
- pypeman/tests/tests_bin.py
kind of what was discussed already
> fix tests and minor refactoring

- pypeman/message.py
- pypeman/nodes.py
- pypeman/tests/common.py
- pypeman/tests/test_debug.py
- pypeman/tests/test_message.py
- pypeman/tests/test_nodes.py
As discussed, this option allow a node to log his output.
> Add BaseNode option to log output message

- pypeman/nodes.py
allows to indent the json output for debugging / etc.
> add indent param to JSON Node

- docs/gettingstarted.rst
- docs/index.rst
- docs/introduction.rst
- docs/testing.rst
- docs/userguide.rst
just some spelling. and changed 'pip install'
> minor doc changes

- .travis.yml
- pypeman/channels.py
- pypeman/contrib/ftp.py
- pypeman/contrib/hl7.py
- pypeman/contrib/http.py
- pypeman/contrib/time.py
- pypeman/contrib/xml.py
- pypeman/endpoints.py
- pypeman/events.py
- pypeman/helpers/reloader.py
- pypeman/nodes.py
- pypeman/pjt_templates.py
- pypeman/tests/common.py
- pypeman/tests/test_channel.py
- pypeman/tests/test_nodes.py
- requirements_test.txt
- tox.ini
No more py34 compatible.
Also fix unnecessary test boilerplate.
> Migrate to py35 asyncio syntax

- pypeman/contrib/http.py
> allow to increase max_size for http posts

- README.md
- pypeman/nodes.py
- pypeman/tests/test_nodes.py
- setup.py
> Fix drop node to allow specific message

- pypeman/commands.py
- requirements.txt
- setup.py
starting / stopping as daemon working now.
I used very simple but not very popular external module.
We have to decide whether we want to add it as dependency or just copy paste its code into the repo
> can now start / stop (as daemon)

- pypeman/test.py
- pypeman/tests/test_app_testing/project.py
- pypeman/tests/test_app_testing/settings.py
- pypeman/tests/test_app_testing/tests.py
- pypeman/tests/test_testing.py
- pypeman/tests/tests_bin.py
- setup.cfg
Add a cleanup action after each test to close the current loop and open a new one.
> Fix #48 Add loop cleanup after each tests

- pypeman/tests/test_remoteadmin.py
With this change unittest passes also on a machine if the TCP port 8091
is used by an application.
The test just picks one unused TCP port.
Coding for the test fixture is a little clumsy as unittests is the parent class
> unittest works now also if port 8091 is used

- CHANGELOG.md
- README.rst
- docs/gettingstarted.rst
- docs/userguide.rst
- pypeman/channels.py
typos, grammar, formatting.
No meaning has been changes.
> minor changes to documentation (only language)

- pypeman/helpers/reloader.py
fix issue https://github.com/mhcomm/pypeman/blob/3f9b4fcc84223ed411b34b70629348028ecea29f/pypeman/helpers/reloader.py#L14
> fix accidentally removed return

- setup.py
for jsonrpcclient, jsonrpcserver and websockets
need a better solution...
> version in setup.py

- .coveragerc
- pypeman/tests/test_import_mods.py
- requirements_test.txt
- tox.ini
uses pytest plugin for coverage
(adds about 5% to coverage)
also add a small test to at least import some mods
> minor changes for coverage

- pypeman/tests/test_channel.py
- pypeman/tests/test_msgstore.py
- pypeman/tests/test_testing.py
They even pass for time travellers.
removed also some dead code
> unit tests pass now also on 12th of a month

- pypeman/commands.py
Should resolve https://github.com/mhcomm/pypeman/issues/54 or at least fix partially
> add signal handlers. minor cleaning

- pypeman/nodes.py
- pypeman/test.py
- pypeman/tests/test_channel.py
- pypeman/tests/test_debug.py
- pypeman/tests/test_imports.py
- pypeman/tests/test_message.py
- pypeman/tests/test_msgstore.py
- pypeman/tests/test_nodes.py
- pypeman/tests/test_remoteadmin.py
- pypeman/tests/test_settings.py
- pypeman/tests/test_testing.py
- pypeman/tests/tests_bin.py
This MR Shall fix  https://github.com/mhcomm/pypeman/issues/72
Checks are performed to ensure uniqeness of nodes, test cases are adapted accordingly
> Dvl/klaus/bug #72

- pypeman/contrib/http.py
display error msg with name of cert files, that can't be found
> explicit error about missing cert files

- pypeman/commands.py
- requirements.txt
- setup.py
PR handling https://github.com/mhcomm/pypeman/issues/121
> replace begins with click. (no unit tests. just tested by using)

- CHANGELOG.md
- pypeman/__init__.py
> bump version / upd CHANGELOG

- pypeman/contrib/http.py
> fix aiohttp new version

- pypeman/commands.py
pypeman pytest accepts now again arbitrary commands
This fixes https://github.com/mhcomm/pypeman/issues/133
> fixing issue #133

- .travis.yml
- tox.ini
handles #137 
unit tests now also with python 3.8
> #137 test now also with python 3.8

- pypeman/commands.py
Handles #129
A very simplistic but working implementation for printsettings.
Could be enhanced to be more similar to django_extensions' print_settings
> simplistic printsettings function for #129

- CHANGELOG.md
- pypeman/__init__.py
- setup.py
also adapt setup.py python version info
> bump version, update and spellfix rls notes.

- .travis.yml
- CHANGELOG.md
- setup.py
- tox.ini
Handles #132
Did nothing to actively destroy compatibility though
> #132 remove python 3.5 from supported versions

- CHANGELOG.md
- pypeman/__init__.py
MR for creating 0.4.0
* remove python 3.5 from supported versions.
* create a node to combine contexts
* some refactoring for better reuse 
* add a sample project
* some  cleanup (comments, rmv py2 code)
* add a first version of a plugin manager. (requires py3.6)
> bump version

- pypeman/channels.py
repr string for channels contains now channel name
> change repr string for channel

- .github/workflows/build.yml
- .travis.yml
try to phase out travis ci and use github actions / work flows
> attempt to use github workflows

- .github/workflows/build.yml
remove pypy tests from workflow.
at the moment they freeze. this has to be analyzed.
let's live without pypy for pypeman meanwhile
> disable pypy tests fo time being

- pypeman/channels.py
helps to avoid inflating log files due to message drops
> avoid a backtrace when subchan drops a message

- pypi-release-cl.md
instructions were old.
Some things changed
> try to improve deployment instructions

- setup.py
Shall fix #238
just a little bigger¸ but allows testing
> add tests to package. fix @238

- pypeman/contrib/http.py
this can be useful for pypeman side authentication
> allow http channel to add headers to meta data

- pypeman/contrib/http.py
- pypeman/msgstore.py
- pypeman/tool_commands.py
- pypeman/tools/send_from_store.py
- pypeman/tools/view_store.py
- setup.py
first shot at pypeman helpers
helpers only partially implemented.
- Helps to filter / print  messages from store
- helps to send messages to an http destination
At the moment only file store supported
> tools: view_store / send_from_store

- pypeman/contrib/http.py
required to allow accessing extranet sides if an http proxy is required
> http request node respects now environment vars

- pypeman/nodes.py
https://github.com/mhcomm/pypeman/issues/294
> Add a reject Node

- pypeman/contrib/http.py
Permits to return binary response to the httpchannel's caller (and set a content_type)
> add http binary response to channel (code from interop)

- pypeman/nodes.py
- pypeman/tests/test_nodes.py
oops I forgot to `git push` and I already merged #302
> allow re-using the same function

- pypeman/channels.py
- pypeman/message.py
- pypeman/nodes.py
- pypeman/tests/test_msgstore.py
Add a store_id and a store_chan_name attr to msg to permits knowing the store id of the parent message that is store
> add store id and store_chan_name attrs to msg

- pypeman/channels.py
rm _call_(init|join|drop|reject|final)_nodes functions and creating a new one _call_special_nodes that replace all of them
> merge special nodes call
