mhcomm/pypeman

.coveragerc
.gitignore
.pylintrc
docs/userguide.rst
pypeman/conf.py
pypeman/default_settings.py
pypeman/nodes.py
pypeman/persistence.py
pypeman/tests/settings/test_settings_persistence.py
pypeman/tests/settings/test_settings_sqlite_persist.py
pypeman/tests/test_nodes.py
requirements.txt
setup.py

Nodes use now persistent data between two pypeman executions to save things like "last execution time" to allow differential running on database for example.

Fix #44 Add persistency data to nodes.

---

pypeman/default_settings.py
pypeman/remoteadmin.py

The current remote interface is not suited to work behind a reverse proxy.
With these minimal changes it is possible to get remote admin coexisting on an existing webserver:
Three redirections are required (If interested I can post an example config for nginx)"
/prefix1/ to redirect to http(s)://pypemanhost:http_port
/prefix2/ to redirect to ws(s)://pypemanhost:ws_port
/configs.js to redirect to http(s)://pypemanhost:http_port/configs.js
With some more  changes the first two redirects should be sufficient. (Perhaps with an href of "../configs.js" ?

allows to use remote admin via a reverse proxy.

---

pypeman/channels.py

file encoding issues due to a bad locale on a system were silently
ingored and not reported.
It might perhaps be helpful to silence some warnings, though at the moment I tend to
silence none of these warnings.
List of a few potential exceptions (there are probably much more):
- files that get created and then deleted/renamed
- file permission issues
- partially written files, that are truncated at a multibyte character in text mode
- file encoding issues of not in binary mode

FileWatcher does no more silence all exceptions.

---

pypeman/contrib/http.py

first call detection was broken and caused http endpoints to fail.

fixes gh-76 : http endpoint doesn't setup route

---

pypeman/contrib/http.py
pypeman/errors.py
pypeman/tests/test_channel.py
pypeman/tests/test_imports.py

socket reuseport option uses a linux feature. It allows two processes to listen on the same port.
With this feature we can start two pypemEn with the same config.
Will be used for soft restart without losing any incoming connection.

socket for http endpoint, REUSEPORT

---

pypeman/remoteadmin.py

connecting to the web admin interface without url (e.g. hocalhost:8090 ) will redirect to the index page.
Less typing + more intuitive for an end user :-)

redirect / to index.html for web admin

---

pytest.ini
requirements_test.txt
setup.cfg
setup.py

Main reason is to allow us in future tests to use pytest-asyncio
https://github.com/pytest-dev/pytest-asyncio
This might resolve some issues in tests. The current test fails for
example on servers where port 8091 is aleady being used as a listening
port seems to be hardcoded.
pytest-asyncio however would allow us to use the 'unused_tcp_port' fixture in order
to provide the test runner with an unused tcp port.
pytest-asyncio has also a 'event_loop' fixture, which might help during test development.

switch over to pytest.

---

pypeman/contrib/hl7.py
pypeman/contrib/http.py
pypeman/endpoints.py
pypeman/tests/test_channel.py

Socket endpoint and reuse_port from unix
In my test, os use the first pypeman each time ...
how test socket in unitest ?

Reuse socket option for MLLP endpoint

---

requirements.txt

The current version failed.
Did not try to find the most recent working version.

freeze version of jsonrpcclient req <=2.5.2

---

pypeman/tests/test_remoteadmin.py

new pytest version doesn't allow explicit call of fixture functions.
Now they're only allowed to be called as decorator.
This MR is required to keep the existing CI  tests up and running.

fix unit tests. new pytest version broke tests

---

pypeman/commands.py
pypeman/default_settings.py

this allows to specify the name of the module, that contains the project
in pypeman settings.
Can come in handy for testing, sub projects, etc.

allow to project module from pypeman settings

---

pypeman/commands.py

This is required for test automation of projects using pypeman.
The current version does not capture the exit code.

ensure, that pytest errors result in an exit code

---

pypeman/channels.py
pypeman/commands.py
pypeman/helpers/sleeper.py
pypeman/tests/tests_bin.py

This should address bug https://github.com/mhcomm/pypeman/issues/55
The implementation is done by creating an interrruptible  Sleeper class.
At the moment each channel will have it's own sleeper class, such, that each channel can be terminated individually.
In order to use the interruptable sleeps
one should use
`await channel.interruptable_sleeper.sleep(interval)`
instead of 
`await asyncio.sleep(interval)`

Dvl/klaus/bug #55

---

.travis.yml
setup.py
tox.ini

as 3.5 is the oldest version still being mentioned in the python docs
we should ensure pypeman still runs with the newer versions.
This PR adds python 3.7 (3.8 cannot be added until https://github.com/mhcomm/pypeman/issues/121 is done)
This PR addresses thus https://github.com/mhcomm/pypeman/issues/116

test with newer python versions

---

pypeman/commands.py

fixes #135 
exit code 0 if all tests pass
other exit codes otherwise (refer to the pytest documentation)

fix #135 pypeman pytest returns now the correct exit code

---

pypeman/channels.py
pypeman/commands.py
pypeman/contrib/ctx.py
pypeman/endpoints.py
pypeman/nodes.py
pypeman/remoteadmin.py
pypeman/test.py
pypeman/tests/common.py
pypeman/tests/pytest_helpers.py
pypeman/tests/test_channel.py
pypeman/tests/test_ctx_nodes.py
pypeman/tests/test_msgstore.py
pypeman/tests/test_remoteadmin.py
pypeman/tests/test_testing.py

Will address #126
CombineCtx node has been added with 4 unit tests
Additional changes:
- `all` is a reserved python word, therefore some renaming:
- - `pypeman.channels.all` -> `pypeman.channels.all_channels`
- - `pypeman.nodes.all` -> `pypeman.nodes.all_channels`
- - `pypeman.endpoints.all` -> `pypeman.endpoints.all_channels`
- add function (for testing) `reset_pypeman_channels`
- add function (for testing) `reset_pypeman_endpoints`
- add a pytest fixture for resetting pypeman graph for each test
- minor fix in pypeman.tests.common (create copy of a dict)

#126 CombineCtx Node + tests

---

pypeman/channels.py

debug logs (that are not really needed) were kept and at warning level

rmv bad logs

---

pypeman/commands.py

when calling pypeman with
pypeman start --cli
one can now call the 'print_graph()' command without importing
as it has been added to the name space

add print_graph command if started with --cli

---

pypeman/contrib/ctx.py

this log logs the entire payload. (all payloads of the contexts
that were combined)
This is not such a good idea.
The log is now removed. Something like that can be added during
development if required.

rmv very noisy combine log

---

pypeman/channels.py
pypeman/tests/test_channel.py

This PR fixes a regression introduced by https://github.com/mhcomm/pypeman/pull/176
Add booloean param `wait_subchans` to BaseChannel
Default = False. If set to True, Channel will wait for subchannels 
(before procesing new messages or returning their status (like "DROPPED" for HttpChannel)

fix speed response (add wait_subchans param)

---

pypeman/client/package-lock.json

manual apply of dependabot PR #181
Bumps [css-what](https://github.com/fb55/css-what) from 2.1.0 to 6.1.0.
- [Release notes](https://github.com/fb55/css-what/releases)
- [Commits](fb55/css-what@v2.1.0...v6.1.0)
---
updated-dependencies:
- dependency-name: css-what dependency-type: indirect ...

manual Bump css-what from 2.1.0 to 6.1.0

---

tox.ini

perhaps older versions were more tolerant.
now `passenv` requires comma separated values

tox ini needs now ',' instead of ' '

---

pypeman/tests/test_channel.py

FIX ftp channel tests that randomly fails due to don't wait end chann process before assert

---

pypeman/contrib/http.py

1: DeprecationWarning: ssl.PROTOCOL_SSLv23 is Deprecated please use ssl.PROTOCOL_TLS instead
2: DeprecationWarning: ssl.PROTOCOL_TLS is deprecated use ssl.PROTOCOL_TLS _CLIENT or ssl.ssl.PROTOCOL_TLS_SERVER instead

rm Deprecation warning

---

pypeman/contrib/http.py

Sometimes, the request fails with a timeout if binary=True, moving the response reader inside the AsyncClientConnection seems to resolve the problem

fix HttpRequest binary=True freeze

---

pypeman/channels.py
pypeman/tests/test_channel.py

If the msg received in entry of the channel is modified by a node, you cannot be sure of what you "inject" in final nodes (the problem could possibly occur in other endnodes).
BUT: final nodes are designed to everytime have the start message in entry.
A simple msg.copy() in the handle resolve the problem (for all endnodes)
FIx endnodes tests
fix test_channel_result because because i don't know why but the Python2Json had a different comportment with the msg.copy:  the result:  with msg:  '{"test1": 1}'  => with msg.copy(): '{"test1":1}'  a space was removed...

fix final endnodes entry msg

---

pypeman/nodes.py
pypeman/tests/test_nodes.py

This PR proposes 2 new nodes: `MsgFuncNode` and `FuncNode`.
It aims at cutting on boilerplate code involved when the operation performed by a node is reducible to only its `process` method.
```py
def _to_zendesk_event(parsed_json):
kind = parsed_json['kind']
if kind == "newticket":
return NewTicketEvent(...)
...
chan.add(
nodes.JsonToPython(),
nodes.FuncNode(_to_zendesk_event),
nodes.Log(),
)
```

MsgFuncNode and FuncNode

---

pypeman/channels.py
pypeman/tests/test_channel.py

Asyncio coroutine that create task ofl himself in a loop could cause some logging problems like duplicate logs

FIX logs in tests

---

pypeman/channels.py
pypeman/contrib/hl7.py
pypeman/contrib/http.py
pypeman/exceptions.py
pypeman/nodes.py
pypeman/tests/test_channel.py
pypeman/tests/test_nodes.py
setup.py

Refactor the call of node's handle (move it in channel's methods instead of nodes)
+
move all exceptions in new exceptions file
+
Change Yielder Behaviour: now if an exception occur during a yielded message, will wait the end of the yield to raise the exception (next sub-messages will be processed)

Refactor nodes call

---

pypeman/channels.py
pypeman/conf.py
pypeman/exceptions.py
pypeman/message.py
pypeman/msgstore.py
pypeman/nodes.py
pypeman/retry.py
pypeman/tests/common.py
pypeman/tests/settings/test_settings_retry_store.py
pypeman/tests/test_channel.py
pypeman/tests/test_msgstore.py
pypeman/tests/test_retrystore.py

Add a RetryStore:
- Add auto_retry_exceptions attr to nodes to catch specific exceptions that must pause the channel and store the message to replay it later
- Add a retryStore that start and stop automatically and permits inject some messages that raises for example a connectTimeout
- The retry store automatically put its channel in paused state at start, and un-pause it at stop
- A Paused channel will put all of its message in the retry store wainting for all retries done
Other changes:
- add seconds and microsecconds in FileMessageStore id to have a more granular order
- add sub message states in message meta to have the history of submessages states
- At end of a channel, the worst state of sub messages is taken as the message state
Bugs with the retry store:
- The change state …

add auto retry

---

pypeman/channels.py
pypeman/msgstore.py
pypeman/nodes.py
pypeman/plugins/remoteadmin/views.py
pypeman/tests/test_msgstore.py

* `BaseNode.store_meta`
* `MessageStore._search_meta_filter_sort`
Adds support for automatically storing metadata of handled messages: the `store_meta` parameter added to `BaseNode`'s constructor must be a set or list of keys; after a message is fully handled, if its associated `.meta` contains values for the given keys, these values are aggregated into the channel's message store. Only string values are expected and stored this way.
The stored metadata can then be used to retrieve messages through the parameter `meta` of `MessageStore.search`. The following filters are handled:
* `text_<name>`: string to search in meta value.
* `rtext_<name>`: string regex to search in meta value.
* `start_<name>` / `end_<name>`: filter a range; values are interpreted and compared as numbers when …

store and search for meta
